### ISSUE TITLE
validation is not correct on ios 

### ISSUE THREAD

**Issue by pradeep-chauhan** [razorpay/razorpay-ios-sample-app#1]
I have implemented razorpay on ios but when i'm entering card number it is not taking card number and year and always showing validation error.

**Comment by akshaybhalotia** [comment]
@pradeep-chauhan 
Could you please drop a mail to support (at) razorpay (dot) com with your merchant ID and the issue you are facing with validation? Since this requires crucial information, we suggest that we take it over email rather than here.
