### ISSUE TITLE
Xcode 10 issue

### ISSUE THREAD

**Issue by kalrashubham49** [razorpay/razorpay-ios-sample-app#12]
Your sample application not working with Xcode 10. 

Showing some problem , Symbol not found, referenced from "RazorPay.framework" in "libSwiftCore.lib". Can you please check ??

**Comment by iThink32** [comment]
We are aware of this issue , it is because Xcode 10 supports Swift 4.2 and above and our framework is compiled with Swift 4.1.We are making a release on September 28th for this , please wait till then.
