### ISSUE TITLE
iPhone X design issues 

### ISSUE THREAD

**Issue by bharat-p-jain** [razorpay/razorpay-ios-sample-app#13]
When integrating iOS SDK, the payment options goes beyond the safe area of iPhone X resulting in "Pay X" button not fully visible. Is this something that can be addressed, as there is no way to control the view launched in SDK. Refer the screenshot.

![simulator screen shot - iphone x - 2018-09-19 at 18 11 54](https://user-images.githubusercontent.com/43410178/45753814-8b3c2d00-bc37-11e8-8712-4244679c971c.png)

**Comment by iThink32** [comment]
Thank you for reporting this issue , we are currently working on it , as of now users have to scroll to access the pay button but we are making a release soon and it will be fixed in that.

**Comment by bharat-p-jain** [comment]
Is there any time frame when the new release is coming out ?

**Comment by iThink32** [comment]
We are making a release on 28th September , please wait till then.

**Comment by iThink32** [comment]
closing as this issue has been fixed.
