### ISSUE TITLE
Is this framework bitcode enabled?

### ISSUE THREAD

**Issue by hemanth2k13** [razorpay/razorpay-ios-sample-app#14]
Hi,

Is this framework bitcode enabled and compiled with swift 4.2 compiler?

When can we expect a pod with bitcode enabled and compiled with swift 4.2?

**Comment by iThink32** [comment]
Yes it is bitcode enabled but not on Swift 4.2.
We are making a release on 28th of September please will till then or use Xcode 9.4.1
