### ISSUE TITLE
dyld: Symbol not found: __T0BOWV XCode 10

### ISSUE THREAD

**Issue by amit-pandey11** [razorpay/razorpay-ios-sample-app#15]
We are facing an issue with SDK on XCode 10: it says :
![screen shot 2018-09-21 at 11 45 51 am](https://user-images.githubusercontent.com/31159792/45879592-b7d08000-bdc2-11e8-9263-83330f53886b.png)

**Comment by gururajphadnis** [comment]
We are also facing the same issue. Had to upgrade to Xcode 10 to support iOS 12 and started getting dyld: Symbol not found: __T0BOWV error.

**Comment by iThink32** [comment]
@amit-pandey11  @gururajphadnis  Xcode 10 uses Swift 4.2 and our latest framework uses Swift 4.1 , we are making a release on 28th September.Please wait till then.

**Comment by vipulasri** [comment]
@iThink32 If this issue is gonna be solved in future then this shouldn't have been marked as closed.

**Comment by iThink32** [comment]
@vipulasri I closed it as information regarding the release date has been provided , no further discussion is required on this issue , if you need further clarifications you are always welcome to create a new issue. 
But I guess it helps people get to know that such an issue exists so keeping it open , thanks for the heads up

**Comment by Mayur-Wadpalliwar** [comment]
@vipulasri You will be able to download the latest framework from: https://razorpay.com/docs/ios/ by tomorrow EOD.
