### ISSUE TITLE
Crash in iOS 10.3.3.

### ISSUE THREAD

**Issue by RohitWellthy** [razorpay/razorpay-ios-sample-app#16]
We have integrated Razorpay in our app and live also. 
Issue : I am trying to do the payment but getting a crash, adding snippet as well as other info :
Kindly, help us out.

Device : iPhone 5s [10.3.3]. 
Xcode : Version 10.1 (10B61)
pod 'razorpay-pod' [1.0.26]
Swift : 4.2

<img width="1003" alt="screen shot 2018-12-12 at 7 30 27 pm" src="https://user-images.githubusercontent.com/33996254/49086625-ff6c0000-f27a-11e8-9be2-f27dd1281c5e.png">

**Comment by iThink32** [comment]
@RohitWellthy are you sure it is an iPhone 5s or an iPhone 5C ? The reason being we do not support iPhones running 32 - bit architecture , i.e iPhone 5c and below.
Please go through the readme for more clarity.

**Comment by RohitWellthy** [comment]
Yes, it's iphone 5s.
Please let me know if you need anything from my end.

**Comment by iThink32** [comment]
@RohitWellthy I have just tested it on our iPhone 5s and it is working fine.Can you try integrating it on an empty test app?

**Comment by RohitWellthy** [comment]
yes , i am doing that.

**Comment by iThink32** [comment]
@RohitWellthy ok.

**Comment by iThink32** [comment]
@RohitWellthy Can you also share your iPhone's serial number ?

**Comment by RohitWellthy** [comment]
Can you recheck the OS Version of your test device.

**Device : iPhone 5s [10.3.3].**
Xcode : Version 10.1 (10B61)
pod 'razorpay-pod' [1.0.26]
Swift : 4.2
 
I just created the sample app and its crashing. I have attached the screenshot.
Let me know if you need anything from my end.

<img width="1129" alt="screen shot 2018-11-28 at 12 43 31 pm" src="https://user-images.githubusercontent.com/33996254/49134924-4570a480-f30b-11e8-8ee1-00888da4579d.png">
![img_0255](https://user-images.githubusercontent.com/33996254/49135321-5cfc5d00-f30c-11e8-8468-1faff3533ab8.PNG)

**Comment by iThink32** [comment]
@RohitWellthy my iOS version is 12 , but can you provide your iPhone's serial number?

**Comment by RohitWellthy** [comment]
On 12 it won't crash.
F17KX4W8DTWG

**Comment by iThink32** [comment]
@RohitWellthy  your device is not an iPhone 5s it is an iPhone 5 , please check your device properly ,
here's the apple link

https://checkcoverage.apple.com/in/en/?sn=F17KX4W8DTWG

**Comment by iThink32** [comment]
@RohitWellthy go through the readme , you'll find all the required information there.

**Comment by RohitWellthy** [comment]
Sorry, it's my bad.

**Comment by iThink32** [comment]
@RohitWellthy no prob , closing as this issue is fixed.

**Comment by RohitWellthy** [comment]
@iThink32  Hey, is there any alternative solution to solve the iphone 5 crash?  Is there any way to make the payment using Razorpay!

**Comment by iThink32** [comment]
@RohitWellthy we do not support iPhone 5 anymore as it uses 32 bit architecture.Even the iOS App Store no longer supports 32 bit apps ,the people using such phones can no longer get updates.It is not wise to support them moving forward.Refer the links below

https://www.cultofmac.com/464817/apple-prepares-drop-support-32-bit-ios-apps/
https://www.wired.com/story/the-ios-11-32-bit-appocalypse-isnt-actually-that-bad/

The only way is see is using an older SDK but it is strongly not recommended as it does not contain latest features/fixes.

**Comment by RohitWellthy** [comment]
Thanks

**Comment by ajith8291** [comment]
Hi @iThink32 

App is crashing after implementing RazorPay SDK(Objective C). It works fine on iOS 13+. But it crashes on iOS 12.0 and 12.1. Can you please help me to resolve this.

**Comment by Nautiyalsachin** [comment]
@ajith8291 try to enable `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES` in build settings.
