### ISSUE TITLE
Same Issue Persist after following everything

### ISSUE THREAD

**Issue by MohitSChauhan** [razorpay/razorpay-ios-sample-app#18]
RazaorPay not launching
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/synoriq/Library/Developer/CoreSimulator/Devices/685DBC43-14F0-45D4-895C-18271B65760F/data/Containers/Bundle/Application/D6534EB6-7F64-4C5A-AE0A-7FECB5415DD1/Guru.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found

**Comment by iThink32** [comment]
@MohitSChauhan which Xcode version are you using? This version will only work on Xcode 10 and above

**Comment by rahveekotadiya** [comment]
Hello @iThink32 i am facing same issue and i have xcode 10.2.1 and i checked that framework added in both place link binary library and also in embeded framworks.

i also enabled embed swift standad lib in build settings but still i am facing this error.

My code is written in objective c. 
Please help me i am stucked here and delayed on app launching.

**Comment by pronav** [comment]
Are you using razorpay pod?

**Comment by rahveekotadiya** [comment]
@pronav no added manualy.

**Comment by pronav** [comment]
Which version of plugin are you using? You can confirm by checking Razorpay header file, which should contain mention of swift compiler (4.2 or 5)

**Comment by rahveekotadiya** [comment]
@pronav Swift 4.2

**Comment by pronav** [comment]
Please download new version from here and replace old framework: https://rzp-mobile.s3.amazonaws.com/ios/checkout/1.2.0/RazorpayBitcodeX10.framework.zip

**Comment by pronav** [comment]
You can follow steps here: https://razorpay.com/docs/ios/

**Comment by rahveekotadiya** [comment]
@pronav Thanks man it's work you saved my day.
