### ISSUE TITLE
how to remove ios simulator architectures

### ISSUE THREAD

**Issue by vandna27** [razorpay/razorpay-ios-sample-app#19]
ld: Plugins/com.razorpay.cordova/Razorpay.framework/Razorpay compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file '/Plugins/com.razorpay.cordova/Razorpay.framework/Razorpay' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vandna27** [comment]
Showing All Messages
 /Plugins/com.razorpay.cordova/Razorpay.framework/Razorpay compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file '/Plugins/com.razorpay.cordova/Razorpay.framework/Razorpay' for architecture armv7

**Comment by shrykg** [comment]
same issue , not able to run sample app

**Comment by pronav** [comment]
sample app works with xcode 10.1 and hasn't been updated to support swift5/10.2 yet

**Comment by Nautiyalsachin** [comment]
Try downloading new sample apps, as they are created with the latest versions of Xcode and includes some of the new updates.

Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a 
new ticket if you have any additional issues.
