### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by pradeep-chauhan** [razorpay/razorpay-ios-sample-app#2]
getting this error when trying to archive the build.

ld: ' You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pradeep-chauhan** [comment]
it's resolved.

**Comment by pradeep-chauhan** [comment]
it's resolved by me.

**Comment by diliplilaramani** [comment]
Hi Pradeep, can you share how did you resolve this error?

**Comment by pradeep-chauhan** [comment]
Enable bitcode and rebuild then compile it.
Note : Cleared cache as well
