### ISSUE TITLE
In XCode 11.2.1 getting Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by globaltakeoff** [razorpay/razorpay-ios-sample-app#20]
In XCode 11.2.1 getting Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

Pls check

**Comment by Nautiyalsachin** [comment]
@globaltakeoff : You can download the latest SDK from [here](https://razorpay.com/docs/payment-gateway/ios-integration/standard/).
