### ISSUE TITLE
[Google Pay UPI Integration] How to integrate Google Pay with Razorpay custom iOS SDK?

### ISSUE THREAD

**Issue by shashankk7** [razorpay/razorpay-ios-sample-app#24]
Hi, I was integrating `Razorpay custom iOS SDK` in my app, and I cannot find any way to integrate `Google Pay` as a mode of UPI payment. There are docs on integration with desktop, chrome, and Android but none is there for iOS. Is there any way by which I can let my user select Google pay option in my app (without asking for VPA), and then Razorpay handles the payment?

**Comment by Nautiyalsachin** [comment]
Hi @shashankk7: We are working on this feature in future releases, right now in iOS we only support collect flow where the user has to provide the VPA manually. And proceed with the transaction in Google Pay. 

Also, this feature will be exposed to Custom SDK on the basis of more merchant demand.
https://github.com/razorpay/razorpay-pod/issues/95
