### ISSUE TITLE
Google Pay opens last selected screen. So user has to go to All transitions and then accept in order to Cash IN

### ISSUE THREAD

**Issue by devauk** [razorpay/razorpay-ios-sample-app#26]
## Problem description

I am facing two issues with UPI based transactions

1. When cash in transaction is initiated we get the notification to approve the request on google app. When tapped on Notification for cash IN via Google pay, Google Pay opens last selected screen. It does not proceed to the truncation page on google pay so user has to go to All transitions and then accept in order to Cash In. Does this requires any thing to be handled from code side? 

2.  Once the payment is done via google pay the control doesn’t not redirect to app automatically, user has to do it manually (Android it happens automatically). How can I achieve this on iOS ?

## Razorpay SDK Version :

v1.2.1

## Xcode Version :
v11.3.1

**Comment by gourabghosh1** [comment]
@devauk can you share your Merchant id please ?

**Comment by devauk** [comment]
> @devauk can you share your Merchant id please ?

D0XUMCGawND8VF

**Comment by gourabghosh1** [comment]
@devauk 

query 1> nothing we can do here (Its called Collect flow) , its Gpay app which is doing the same.
query 2> As of now auto redirect to app in IOS is not feasible. Only android.

**Comment by devauk** [comment]
> @devauk
> 
> query 1> nothing we can do here (Its called Collect flow) , its Gpay app which is doing the same.
> query 2> As of now auto redirect to app in IOS is not feasible. Only android.

ok, noted

**Comment by Nautiyalsachin** [comment]
Hi @devauk, we are supporting redirect in iOS now for UPI apps, right now we only support Google Pay, Paytm and Phone Pe. Here is the [link](https://razorpay.com/docs/payment-gateway/ios-integration/standard/#enable-upi-intent-on-ios) with the steps to enable it in iOS.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to no responses. Feel free to re-open this issue.
