### ISSUE TITLE
Custom payment help

### ISSUE THREAD

**Issue by rahuldange09** [razorpay/razorpay-ios-sample-app#28]
## Description

Hello, i was implementing custom payment for ios and I came across thing that in docs it's not mentioned at all that when user closes, cancels payment what to do, How to inform razorpay that this is user cancelled transaction.

So I checked sdk methods and I came across two methods "userCancelledPayment" and "close". I'm confused which one to call and what is difference between them. Again I don't find any commnets on that methods also.
Please help me out.

## Razorpay SDK Version :

Using "Razorpay Custom UI 1.3.4" for Swift 5.1+

## Xcode Version :
11.3.1

**Comment by Sumit738** [comment]
Please refer the below link -
https://razorpay.com/docs/payment-gateway/ios-integration/custom/#step-7---handle-success-and-error-events

**Comment by rahuldange09** [comment]
Hello,
Thanks for the reply,
I checked it. So you mean I should just call  "userCancelledPayment()" only? right?

**Comment by Nautiyalsachin** [comment]
Hi @rahuldange09, yes you have to call "userCancelledPayment()" only, and this will tell Razorpay that you have cancelled the payment, we will proceed afterwards. Closing this issue now, feel free to re-open it.
