### ISSUE TITLE
Getting error while run on xcode 12 GM

### ISSUE THREAD

**Issue by kalathiyanilesh1** [razorpay/razorpay-ios-sample-app#31]
![Screenshot 2020-09-17 at 6 29 20 PM](https://user-images.githubusercontent.com/27014642/93473542-c3080900-f913-11ea-8590-baa22ce7865c.png)
- when i try to run my project in xcode 12 gm i got razorpay error like "'Razorpay' is unavailable: cannot find Swift declaration for this class"
i already import Razorpay in it class.

**Comment by Nautiyalsachin** [comment]
Hi @kalathiyanilesh1 please update the code to 

`        razorpay = RazorpayCheckout.initWithKey(razorpayKey, andDelegate: self)
`

Also, can you tell me from where did you took the reference, I'll update there.

**Comment by kalathiyanilesh1** [comment]
okay, so i need to update the pod & make reference of RazorpayCheckout right?

**Comment by Nautiyalsachin** [comment]
Yes @kalathiyanilesh1, you can just update the pods and update your code, it will start working.

**Comment by kalathiyanilesh1** [comment]
Yes it's working now. Thanks
