### ISSUE TITLE
Adding a notes checkout field in the options dictionary crashes the app

### ISSUE THREAD

**Issue by anuj-rajput** [razorpay/razorpay-ios-sample-app#5]
Referring to the documentation [here](https://docs.razorpay.com/docs/ios#section-step-3-pass-payment-options-and-show-checkout-form), when adding custom notes key in the dictionary, the app crashes.
I am passing the following dictionary to the  `-[Razorpay open:]` function

```
NSDictionary *options = @{
	@"amount": @"100",
	@"name": "Title of Payment",
	@"notes": @{
		@"id": @"352", 
		@"name": @"Anuj", 
		@"orderId": @"220"
	}
};
```

**Comment by akshaybhalotia** [comment]
Hi @anuj-rajput ,

I'm unable to recreate the above said scenario. Can you please help me with your logs or your code?

nitpick: you are missing a `@` in the value of `name`

**Comment by anuj-rajput** [comment]
Hi @akshaybhalotia,
Oh that was a typo.
I figured out that I was using string pointers in the options dictionary instead of actual strings which was causing the crash.
