### ISSUE TITLE
Create custom UI for razorpay

### ISSUE THREAD

**Issue by manojkraftly** [razorpay/razorpay-ios-sample-app#6]
Hi 
I am getting crash with latest sdk when i am using in Xcode 9.2, please check screen shot.

![screen shot 2018-03-23 at 5 38 21 pm 1](https://user-images.githubusercontent.com/36626338/37889326-5562d7ee-30e9-11e8-9cf0-0e1550486cfa.png)

**Comment by AbhinavArora95** [comment]
Please make sure that you have followed all the steps mentioned in our documentation, especially step no. 6 at https://razorpay.com/docs/ios/#for-swift

**Comment by manojkraftly** [comment]
Yes i followed this link:- https://razorpay.com/docs/ios-customui-sdk/#ios-9-update

**Comment by manojkraftly** [comment]
Hi i need to implement custom UI where i can fill card details so please
tell me why i am getting crash when i followed document. Please check screen shot & let me know what i did wrong.

**Comment by AbhinavArora95** [comment]
Please attach the full integration code.

**Comment by manojkraftly** [comment]
Please check this screen shot here i have initialized razorpay with key,
after that i have created dictionary to pass all required info.

**Comment by manojkraftly** [comment]
Please check this screen shot here i have initialized razorpay with key, after that i have created dictionary to pass all required info. 

https://razorpay.com/docs/ios-customui-sdk/

![screen shot 2018-03-26 at 11 49 37 am](https://user-images.githubusercontent.com/36626338/37889896-142a92d2-30ec-11e8-95a1-708f4860bab9.png)

**Comment by AbhinavArora95** [comment]
Please email us at support@razorpay.com with the error and your integration code.

**Comment by manojkraftly** [comment]
Thanks let me send mail to Support

**Comment by Yash-iOS** [comment]
I have started Razorpay iOS Custom UI implementations And I also updated the Razorpay SDK
I am getting crash with the latest SDK when I am using in Xcode 10.2, please check screenshot.
Please check screenshot & let me know what I did wrong.

![Screenshot_Razorpay_SDK_Crash](https://user-images.githubusercontent.com/49909780/56582340-ae2b2700-65f4-11e9-9149-9d776d1d5efd.png)

Please make sure that you mentioned in your document whether all the steps are correct. [](https://razorpay.com/docs/ios-customui-sdk/)

Thanks & Regards
Saurabh Gupta

**Comment by rahuldange09** [comment]
@manojkraftly How you fixed this issue. I'm also facing same issue. Can you please let us know
