### ISSUE TITLE
Provision for Razorpay External wallet integration

### ISSUE THREAD

**Issue by raghunathkavuri** [razorpay/razorpay-ios-sample-app#8]
Hi Team,

As per the code below from the sample iOS app, do we still have the provision for external wallet like PayTM and others for integration with Razorpay?

![image](https://user-images.githubusercontent.com/975730/39870769-23ac5b98-5480-11e8-8de4-416d8ef8a3a6.png)

**Comment by Mayur-Wadpalliwar** [comment]
Yes. You can refer this: https://docs.razorpay.com/v1/page/listing-external-wallets
